services:
  db:
    image: postgres:16-alpine
    container_name: dm-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 15

  app:
    image: ghcr.io/sejuno/delivery-management-app:latest
    container_name: delivery-management
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      KAKAO_LOCAL_REST_API_KEY: ${KAKAO_KEY}
      AI_OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET : ${JWT_SECRET}
      JWT_EXPIRATION : ${EXPIRATION}
    ports:
      - "18080:8080"
    restart: unless-stopped

volumes:
  pgdata:
