spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        highlight_sql: true
        jdbc.time_zone: Asia/Seoul

  # OpenAI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com/v1
      chat:
        options:
          model: gpt-4o-mini
    retry:
      max-attempts: 2
      backoff:
        initial-interval: 500ms

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# JWT
jwt:
  secret: ${JWT_SECRET}
  expiration: ${EXPIRATION}